python main.py \
    --detail_log 1 \
    --port 17587 \
    --save_prefix en \
    --do_train 0 \
    --do_short 0 \
    --seed 1 \
    --g 1\
    --train_path '../../woz-data/MultiWOZ_2.1/train_data.json' \
    --dev_path '../../woz-data/MultiWOZ_2.1/dev_data.json' \
    --test_path '../../woz-data/MultiWOZ_2.1/test_data.json' \
    --max_length 512 \
    --test_batch_size 8 \